required = ["github.com/caicloud/nirvana/utils/api"]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/google/go-github"
  version = "24.0.1"

[[constraint]]
  name = "github.com/xanzy/go-gitlab"
  # Limit version for GitLab v3
  version = "0.4.0"

[[constraint]]
  name = "gopkg.in/xanzy/go-gitlab.v0"
  # Limit version for GitLab v4
  version = "0.19.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  version = "2.0.0"

[[constraint]]
  name = "gopkg.in/h2non/gock.v1"
  version = "1.0.8"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/gengo"
  branch = "master"

[[constraint]]
  name = "github.com/PaesslerAG/jsonpath"
  branch = "master"

[[override]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "1c7c27d043c2a5e513a44084d2b10d77d1402b8c"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[override]]
  name = "github.com/caicloud/nirvana"
  branch = "master"

[[override]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[override]]
  name = "github.com/prometheus/client_model"
  revision = "99fa1f4be8e564e8a6b613da7fa6f46c9edafc6c"

[[constraint]]
  name = "github.com/cbroglie/mustache"
  version = "1.0.1"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mozillazg/go-slugify"
  version = "v0.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.5"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"
[[constraint]]
  branch = "master"
  name = "github.com/gogs/go-gogs-client"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.5.0"

[[constraint]]
  name = "github.com/parnurzeal/gorequest"
  version = "0.2.16"

[[constraint]]
  branch = "master"
  name = "code.gitea.io/sdk"

[[constraint]]
  name = "code.gitea.io/gitea"
  version = "1.10.0"
